# Generated by Django 5.1.2 on 2024-10-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
                ('university', models.IntegerField()),
            ],
        ),
    ]
