# Generated by Django 5.1.2 on 2024-10-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_dates', '0002_alter_data_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='birthday',
            field=models.TimeField(),
        ),
    ]
